INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('A Swirled of Difference',FALSE,FALSE,NULL,'Target');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Americone Dream',FALSE,TRUE,9,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Bourbon Pecan Pie',FALSE,TRUE,7,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Banana Split',TRUE,TRUE,8,'Walmart');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Blonde Ambition',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Boom Chocolatta Cookie Core',FALSE,TRUE,4,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Brewed to Matter',FALSE,TRUE,3,'Target');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Brownie Batter Core',FALSE,TRUE,7,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Cheesecake Brownie',FALSE,TRUE,4,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Cherry Garcia',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Chocolate Cherry Garcia',FALSE,TRUE,7,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Chocolate Chip Cookie Dough',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Chocolate Fudge Brownie',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Chocolate Therapy',FALSE,TRUE,9,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Chubby Hubby',FALSE,TRUE,9,'Randalls');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Chunky Monkey',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Cinnamon Buns',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Coconuts for Caramel Core',FALSE,TRUE,2,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Coffee Toffee Bar Crunch',TRUE,TRUE,7,'Randalls');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Coffee Coffee Buzz Buzz',TRUE,FALSE,NULL,'Randalls');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Confetti Cake',FALSE,FALSE,NULL,'Walmart');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Cookies and Cream Cheesecake Core',FALSE,TRUE,5,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Everything but the...',FALSE,TRUE,5,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Half Baked',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Karamel Sutra Core',FALSE,TRUE,5,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Keep Caramel and Cookie On',FALSE,TRUE,9,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Milk and Cookies',FALSE,TRUE,9,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Mint Chocolate Cookie',TRUE,TRUE,8,'Randalls');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('New York Super Fudge Chunk',FALSE,TRUE,9,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Oat of This Swirled',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('One Love',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Peanut Buttah Cookie Core',FALSE,TRUE,9,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Peanut Butter Cup',FALSE,TRUE,6,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Peanut Butter Fudge Core',FALSE,TRUE,4,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Peanut Butter World',FALSE,TRUE,5,'Target');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Phish Food',FALSE,TRUE,9,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Pistachio Pistachio',FALSE,TRUE,7,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Pumpkin Cheesecake',TRUE,FALSE,NULL,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Red Velvet Cake',FALSE,FALSE,NULL,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('S''mores',TRUE,TRUE,9,'Randalls');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Salted Caramel Almond',TRUE,TRUE,8,'Randalls on W 34th');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Salted Caramel Core',TRUE,TRUE,8,'Randalls');
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Spectacular Speculoos Cookie Core',FALSE,TRUE,7,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Strawberry Cheesecake',FALSE,TRUE,7,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('The Tonight Dough',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Triple Caramel Chunk',FALSE,FALSE,NULL,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Truffle Kerfuffle',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Urban Bourban',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Vanilla',TRUE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Vanilla Caramel Fudge',FALSE,FALSE,NULL,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Vanilla Toffee Bar Crunch',FALSE,TRUE,7,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Cherry Garcia FroYo',FALSE,FALSE,NULL,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Chocolate Fudge Brownie FroYo',TRUE,FALSE,NULL,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Half Baked FroYo',FALSE,TRUE,8,NULL);
INSERT INTO flavors(flavor_name,personal_stock,tasted,rating,retailer_name) VALUES ('Phish Food FroYo',FALSE,FALSE,NULL,NULL);
